USE [master]
GO
/****** Object:  Database [Gelir_Gider_Takip]    Script Date: 10.02.2022 08:27:50 ******/
CREATE DATABASE [Gelir_Gider_Takip]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Gelir_Gider_Takip', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQL2017\MSSQL\DATA\Gelir_Gider_Takip.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Gelir_Gider_Takip_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQL2017\MSSQL\DATA\Gelir_Gider_Takip_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Gelir_Gider_Takip] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Gelir_Gider_Takip].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Gelir_Gider_Takip] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET ARITHABORT OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET  MULTI_USER 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Gelir_Gider_Takip] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Gelir_Gider_Takip] SET QUERY_STORE = OFF
GO
USE [Gelir_Gider_Takip]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Gelir_Gider_Takip]
GO
/****** Object:  Table [dbo].[GIDER_TIPLERI]    Script Date: 10.02.2022 08:27:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GIDER_TIPLERI](
	[gdr_RECno] [int] IDENTITY(1,1) NOT NULL,
	[gdr_Gider_Kod] [nvarchar](50) NULL,
	[gdr_Gider_Ad] [nvarchar](50) NULL,
 CONSTRAINT [PK_GIDER_TIPLERI] PRIMARY KEY CLUSTERED 
(
	[gdr_RECno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GELIR_GIDER_KAYITLARI]    Script Date: 10.02.2022 08:27:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GELIR_GIDER_KAYITLARI](
	[ggr_RECno] [int] IDENTITY(1,1) NOT NULL,
	[ggr_tarih] [datetime] NULL,
	[ggr_tipi] [nvarchar](50) NULL,
	[ggr_gider_tipi] [nvarchar](50) NULL,
	[ggr_cari] [nvarchar](500) NULL,
	[ggr_tutar] [float] NULL,
	[ggr_aciklama] [nvarchar](max) NOT NULL,
	[ggr_kayit_tarih] [datetime] NULL,
 CONSTRAINT [PK_GELIR_GIDER_KAYITLARI] PRIMARY KEY CLUSTERED 
(
	[ggr_RECno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  UserDefinedFunction [dbo].[fn_GelirGiderListesi]    Script Date: 10.02.2022 08:27:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [dbo].[fn_GelirGiderListesi]
(	
	@param as int
)
RETURNS TABLE 
AS
RETURN 
(
SELECT [ggr_RECno] as KAYITNO
      ,[ggr_tarih] as [Tarih]
      ,[ggr_tipi] as [Tipi]
      ,[ggr_gider_tipi] as [Gider Tip Kod]
	  ,(select gdr_Gider_Ad from GIDER_TIPLERI where gdr_Gider_Kod = [ggr_gider_tipi]) as [Gider Tipi]
      ,[ggr_cari] as [Cari]
      ,[ggr_tutar] as [Tutar]
      ,[ggr_aciklama] as [Açıklama]
      ,[ggr_kayit_tarih] as [Kayıt Tarihi]
  FROM [dbo].[GELIR_GIDER_KAYITLARI]


)
GO
USE [master]
GO
ALTER DATABASE [Gelir_Gider_Takip] SET  READ_WRITE 
GO
